//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// -------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ResW File Code Generator (http://bit.ly/reswcodegen)
//     ResW File Code Generator was written by Christian Resma Helle
//     and is under GNU General Public License version 2 (GPLv2)
// 
//     Code generation environment:
//         Time and Date: 4/13/2025 10:42:43 PM (UTC-08:00) Pacific Time (US & Canada)
//         Computer Name: taz-master-x.mysticpop.net
//         User Name    : MYSTICPOP\John Tasler
// 
//     This code contains a helper class exposing property representations
//     of the string resources defined in the specified .ResW file
// </auto-generated>
// -------------------------------------------------------------------------------
namespace Tasler.UI.Properties
{
    using global::Windows.ApplicationModel.Resources;
    
    
    internal sealed partial class Resources
    {
        
        private static ResourceLoader resourceLoader;
        
        /// <summary>
        /// Get or set ResourceLoader implementation
        /// </summary>
        public static ResourceLoader Resource
        {
            get
            {
                if ((resourceLoader == null))
                {
                    Resources.Initialize();
                }
                return resourceLoader;
            }
            set
            {
                resourceLoader = value;
            }
        }
        
        /// <summary>
        /// Localized resource similar to "{0} Minimum:{1} Maximum:{2} Value:{3}"
        /// </summary>
        public static string ToStringFormatString_RangeBase
        {
            get
            {
                return Resource.GetString("ToStringFormatString_RangeBase");
            }
        }
        
        public static void Initialize()
        {
            string executingAssemblyName;
            executingAssemblyName = global::System.Reflection.Assembly.GetEntryAssembly().GetName().Name;
            string currentAssemblyName;
            currentAssemblyName = typeof(Resources).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1].Trim();
            if (global::Windows.UI.Core.CoreWindow.GetForCurrentThread() != null)
            {
                if (executingAssemblyName.Equals(currentAssemblyName))
                {
                    resourceLoader = ResourceLoader.GetForCurrentView("Resources");
                }
                else
                {
                    resourceLoader = ResourceLoader.GetForCurrentView(currentAssemblyName + "/Resources");
                }
            }
            else
            {
                if (executingAssemblyName.Equals(currentAssemblyName))
                {
                    resourceLoader = ResourceLoader.GetForViewIndependentUse("Resources");
                }
                else
                {
                    resourceLoader = ResourceLoader.GetForViewIndependentUse(currentAssemblyName + "/Resources");
                }
            }
        }
    }
}
