//-------------------------------------------------------------------------------------------------
// <auto-generated>
//
//   DO NOT EDIT THIS FILE!
//
//   This code was automatically generated from a Text Template.
//     Time and Date: 9/9/2018 7:38:43 PM (UTC-08:00) Pacific Time (US & Canada)
//     Computer Name: taz-master-x.mysticpop.net
//     User Name    : MYSTICPOP\John Tasler
//
//   Changes to this file may cause incorrect behavior and will be lost when
//   the code is regenerated.
//
// </auto-generated>
//-------------------------------------------------------------------------------------------------


using System.Reflection;

// Version information for an assembly consists of the following four values:
//
//   Major Version  : The four-digit year of the date and time of build.
//   Minor Version  : The month and day-of-month of the date and time of the build.
//   Release Number : The hour and minute of the date and time of the build.
//   Revision       : The second and millisecond of the date and time of the build
//
[assembly: AssemblyVersion("2018.0909.1938.43700")]
[assembly: AssemblyFileVersion("2018.0909.1938.43700")]

