//-------------------------------------------------------------------------------------------------
// <auto-generated>
//
//   DO NOT EDIT THIS FILE!
//
//   This code was automatically generated from a Text Template.
//     Time and Date: 12/27/2017 1:18:28 AM (UTC-08:00) Pacific Time (US & Canada)
//     Computer Name: taz-master-x.mysticpop.net
//         User Name: MYSTICPOP\john tasler
//
//   Changes to this file may cause incorrect behavior and will be lost when
//   the code is regenerated.
//
// </auto-generated>
//-------------------------------------------------------------------------------------------------


using System.Reflection;

// Version information for an assembly consists of the following four values:
//
//      Major Version  : The four-digit year of the build.
//      Minor Version  : The month and day-of-month of the build.
//      Release Number : The hour and minute of the build.
//      Revision       : Unused. Always zero.
//
[assembly: AssemblyVersion("2017.1227.0118.0")]
[assembly: AssemblyFileVersion("2017.1227.0118.0")]

