//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tasler.Windows.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tasler.Windows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationsSettingsExtensions.ClearAutoSaveDeferral called without first calling SetAutoSaveDeferral..
        /// </summary>
        internal static string ClearAutoSaveDeferralCalledBeforeSetAutoSaveDeferral {
            get {
                return ResourceManager.GetString("ClearAutoSaveDeferralCalledBeforeSetAutoSaveDeferral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve view of type {0}..
        /// </summary>
        internal static string CouldNotResolveViewOfTypeFormat1 {
            get {
                return ResourceManager.GetString("CouldNotResolveViewOfTypeFormat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current application is not a HostedApplication. Ensure that the application is properly initialized..
        /// </summary>
        internal static string CurrentApplicationIsNotHostedApplication {
            get {
                return ResourceManager.GetString("CurrentApplicationIsNotHostedApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HostedView must be used within a HostedApplication..
        /// </summary>
        internal static string HostedViewMustBeUsedWithinHostedApplication {
            get {
                return ResourceManager.GetString("HostedViewMustBeUsedWithinHostedApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Type must be assignable to UIElement: {0}.
        /// </summary>
        internal static string HostedViewTypeMustBeUIElementFormat1 {
            get {
                return ResourceManager.GetString("HostedViewTypeMustBeUIElementFormat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect use of WindowPersistence. Both Settings and Key must be specified..
        /// </summary>
        internal static string IncorrectUseOfWindowPersistence {
            get {
                return ResourceManager.GetString("IncorrectUseOfWindowPersistence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TreeRootNodeViewModelBase.CreateChildCollection override must return a non-null collection of type &apos;{0}&apos;..
        /// </summary>
        internal static string MustCreateChildCollectionOfTypeFormat1 {
            get {
                return ResourceManager.GetString("MustCreateChildCollectionOfTypeFormat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; is not attachable to elements of type &apos;{1}&apos;.
        /// </summary>
        internal static string PropertyNotAttachableToTypeFormat2 {
            get {
                return ResourceManager.GetString("PropertyNotAttachableToTypeFormat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is not registered in the service collection..
        /// </summary>
        internal static string TypeNotRegisteredInHostFormat1 {
            get {
                return ResourceManager.GetString("TypeNotRegisteredInHostFormat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter type {0} does not derive from {1}.
        /// </summary>
        internal static string UnexpectedParameterTypeExceptionFormat_2 {
            get {
                return ResourceManager.GetString("UnexpectedParameterTypeExceptionFormat_2", resourceCulture);
            }
        }
    }
}
